# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestStackoverflow():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_stackoverflow(self):
    # Test name: stackoverflow
    # Step # | name | target | value
    # 1 | open | https://stackoverflow.com/users/login | 
    self.driver.get("https://stackoverflow.com/users/login")
    # 2 | setWindowSize | 1524x812 | 
    self.driver.set_window_size(1524, 812)
    # 3 | click | id=email | 
    self.driver.find_element(By.ID, "email").click()
    # 4 | type | id=email | omri@mefathim.co.il
    self.driver.find_element(By.ID, "email").send_keys("omri@mefathim.co.il")
    # 5 | click | id=password | 
    self.driver.find_element(By.ID, "password").click()
    # 6 | type | id=password | &mu%bgEH^qS66CL
    self.driver.find_element(By.ID, "password").send_keys("&mu%bgEH^qS66CL")
    # 7 | click | id=submit-button | 
    self.driver.find_element(By.ID, "submit-button").click()
    # 8 | click | css=.js-site-switcher-button | 
    self.driver.find_element(By.CSS_SELECTOR, ".js-site-switcher-button").click()
    # 9 | click | linkText=log out | 
    self.driver.find_element(By.LINK_TEXT, "log out").click()
    # 10 | click | css=.s-label | 
    self.driver.find_element(By.CSS_SELECTOR, ".s-label").click()
    # 11 | click | css=.s-btn__primary:nth-child(1) | 
    self.driver.find_element(By.CSS_SELECTOR, ".s-btn__primary:nth-child(1)").click()
    # 12 | close |  | 
    self.driver.close()
  
